apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: nestjs-template
    labels:
        app: postgresdb
type: Opaque
data:
    POSTGRES_USER: cm9vdA==
    POSTGRES_PASSWORD: bXlwYXNzd29yZA==

